//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopsSnitch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CopsBaseEntities1 : DbContext
    {
        private static CopsBaseEntities1 _context;
        public CopsBaseEntities1()
            : base("name=CopsBaseEntities1")
        {
        }

        public static CopsBaseEntities1 GetContext()
        {
            if (_context == null)
                _context = new CopsBaseEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarAccident> CarAccident { get; set; }
        public virtual DbSet<Cops> Cops { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Protocol> Protocol { get; set; }
        public virtual DbSet<PTS> PTS { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
