//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopsSnitch.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CopsBaseEntities : DbContext
    {
        public CopsBaseEntities()
            : base("name=CopsBaseEntities")
        {
        }
        private static CopsBaseEntities _context;

        public static CopsBaseEntities GetContext()
        {
            if (_context == null)
                _context = new CopsBaseEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarAccident> CarAccident { get; set; }
        public virtual DbSet<Cops> Cops { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Protocol> Protocol { get; set; }
        public virtual DbSet<PTS> PTS { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
