//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopsSnitch.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocol
    {
        public int Id { get; set; }
        public string IncidentAmount { get; set; }
        public System.DateTime DateOfPayment { get; set; }
        public int CopsId { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Cops Cops { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
