//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopsSnitch.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTS
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public string RegistrNumber { get; set; }
        public string NumberVIN { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public string HP { get; set; }
        public string TipTS { get; set; }
        public string ColorCar { get; set; }
        public string Weight { get; set; }
        public System.DateTime YearOfIssue { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
